# Generated by Django 4.2.7 on 2023-12-01 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 1, 2, 2, 52, 630840, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
